# Generated by Django 2.2.4 on 2020-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200706_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, default='/media/default.png', max_length=2038, null=True),
        ),
    ]
