# Generated by Django 4.0.4 on 2022-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_post_options_post_image_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'uncategorized'), ('foreign', 'foreign'), ('local', 'local'), ('sports', 'sports'), ('politics', 'politics'), ('technology', 'technology'), ('science', 'science'), ('finace', 'finace'), ('education', 'education'), ('how-to', 'how-to'), ('lifeStyle', 'lifeStyle'), ('gossip', 'gossip')], default='uncategorized', max_length=50),
        ),
    ]
