# Generated by Django 2.2.4 on 2020-07-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200706_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='additional_information',
        ),
    ]
