# Generated by Django 4.0.2 on 2022-02-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_bod_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('Politics', 'Politics'), ('Tech/Sci', 'Tech/Sci'), ('How To', 'How To'), ('LifeStyle', 'LifeStyle'), ('Art & Entertainment', 'Art & Entertainment')], default='uncategorized', max_length=50),
        ),
    ]
