# Generated by Django 2.2.4 on 2020-07-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_post_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, default='/divdev+pictures/default.png', max_length=2038, null=True),
        ),
    ]
