# Generated by Django 4.0.2 on 2022-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_category_name_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Text limit is 100, and know that this is the post image description', max_length=100, null=True),
        ),
    ]
