# Generated by Django 4.0.4 on 2022-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='hashtag', to='users.post'),
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
