# Generated by Django 4.0.2 on 2022-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_category_post_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_media/%y/%m'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('Politics', 'Politics'), ('Technology', 'Technology'), ('Science', 'Science'), ('How-To', 'How-To'), ('LifeStyle', 'LifeStyle'), ('Gossip', 'Gossip')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(help_text='Text limit is 200, and know that this is the post snippet', max_length=200),
        ),
    ]
