# Generated by Django 4.0.2 on 2022-02-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_comment_id_alter_hashtag_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('World', 'world'), ('Politics', 'politics'), ('Technology', 'technology'), ('Science', 'science'), ('Finace', 'finace'), ('How-To', 'how-to'), ('LifeStyle', 'lifeStyle'), ('Gossip', 'gossip')], default='uncategorized', max_length=50),
        ),
    ]
