# Generated by Django 4.0.2 on 2022-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_post_views_post_votes_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'uncategorized'), ('world', 'world'), ('politics', 'politics'), ('technology', 'technology'), ('science', 'science'), ('finace', 'finace'), ('how-To', 'how-to'), ('lifeStyle', 'lifeStyle'), ('gossip', 'gossip')], default='uncategorized', max_length=50),
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='users.HashTag'),
        ),
    ]
