# Generated by Django 4.0.2 on 2022-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_post_category_remove_post_hashtag_post_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='hashtag', to='users.HashTag'),
        ),
    ]
