# Generated by Django 4.0.2 on 2022-03-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_post_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(blank=True, default='static/default_jpg.png', max_length=3080, null=True),
        ),
    ]
