# Generated by Django 4.0.2 on 2022-03-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_post_votes_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'uncategorized'), ('foreign', 'foreign'), ('local', 'local'), ('sports', 'sports'), ('politics', 'politics'), ('technology', 'technology'), ('science', 'science'), ('finace', 'finace'), ('education', 'education'), ('how-To', 'how-to'), ('lifeStyle', 'lifeStyle'), ('gossip', 'gossip')], default='uncategorized', max_length=50),
        ),
    ]
