# Generated by Django 4.0.2 on 2022-03-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unwanted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
