# Generated by Django 4.0.2 on 2022-03-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_post_unwanted_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unwanted_content',
        ),
        migrations.AddField(
            model_name='post',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
    ]
